spring:
  application:
    name: animal-name-service

logging:
  level:
    root: INFO
  pattern:
    level: "[%X{userName}] [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"

zipkin:
  endpoint: http://127.0.0.1:9411/api/v2/spans

server:
  port: 9000
