spring:
  application:
    name: name-generator-service

logging:
  level:
    root: INFO
  pattern:
    level: "[%X{userName}] [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"

server:
  port: 8080

zipkin:
  endpoint: http://127.0.0.1:9411/api/v2/spans

services:
  urls:
    animal-service: "http://localhost:9000/api/v1"
    scientist-service: "http://localhost:8090/api/v1"
